version: '3'
services:
  zookeeper:
  image: wurstmeister/zookeeper
  networks:
    - network1
  ports:
    - 2181:2181
  kafka:
  image: wurstmeister/kafka
  networks:
    - network1
  ports:
    - 9092:9092
  depends_on:
    - zookeeper
  environment:
    KAFKA_LISTENERS: PLAINTEXT://:9092
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CREATE_TOPICS: "Stocks:2:1,Quotes:2:1,Orders:2:1"
app:
  restart: always
  build: ./spring-docker
  working_dir: /spring-docker
  volumes:
    - ./spring-docker:/spring-docker
  expose:
    - "8080"
  command: mvn clean spring-boot:run
  networks:
    - network1
  depends_on:
    - zookeeper
networks:
  network1:
    driver: bridge

